# NUMPY-NUMERICAL PYTHON

In [2]:
import numpy

In [3]:
a=numpy.array([1,2,3,4,5,6,7])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
a.size

7

In [5]:
b=numpy.array([100,200,300,400,500,600,700,800,900,1000])

In [6]:
b

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [7]:
b.size

10

In [4]:
import numpy as np

In [9]:
c=np.array([10,20,30,40,50,60,70])

In [10]:
c

array([10, 20, 30, 40, 50, 60, 70])

In [11]:
c.size

7

In [12]:
d=np.array([101,202,303,404,505,606,707],dtype=int)                     #dtype=datatype

In [13]:
d

array([101, 202, 303, 404, 505, 606, 707])

In [14]:
d.dtype

dtype('int32')

In [15]:
c.min()

10

In [16]:
d.max()

707

In [27]:
e=np.array([111,225,332,454,210],dtype='int64')

In [28]:
e

array([111, 225, 332, 454, 210], dtype=int64)

In [29]:
e.dtype

dtype('int64')

In [85]:
type(e)

numpy.ndarray

In [30]:
e.itemsize

8

In [40]:
e.shape

(5,)

In [63]:
e.ndim

1

In [31]:
f=np.array([101,625,342,424,200],dtype='float')

In [32]:
f

array([101., 625., 342., 424., 200.])

In [42]:
g=np.array([101.3,625.6,342.9,424.4,720.2])

In [34]:
g.dtype

dtype('float64')

In [43]:
g

array([101.3, 625.6, 342.9, 424.4, 720.2])

In [5]:
a1=np.array([[1,2,3,4,5],[8,9,10,11,12]],dtype='int64')

In [6]:
a1

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12]], dtype=int64)

In [7]:
a1.shape

(2, 5)

In [60]:
a1.size

14

In [84]:
type(a1)

numpy.ndarray

In [59]:
a1.itemsize

8

In [62]:
a1.ndim

2

In [9]:
a1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  8],
       [ 9, 10],
       [11, 12]], dtype=int64)

In [83]:
type(a1)

numpy.ndarray

In [69]:
b1=np.array([[10,20,30,40,50,60,70,80],[101,202,303,404,505,606,707,808]])

In [70]:
b1

array([[ 10,  20,  30,  40,  50,  60,  70,  80],
       [101, 202, 303, 404, 505, 606, 707, 808]])

In [90]:
b1.ravel()

array([ 10,  20,  30,  40,  50,  60,  70,  80, 101, 202, 303, 404, 505,
       606, 707, 808])

In [82]:
type(b1)

numpy.ndarray

In [71]:
b1.size

16

In [72]:
b1.shape

(2, 8)

In [73]:
b1.reshape(4,4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [101, 202, 303, 404],
       [505, 606, 707, 808]])

In [77]:
c1=np.arange(20)

In [78]:
c1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
c1.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [80]:
c1.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [81]:
type (c1)

numpy.ndarray

In [93]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [95]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [96]:
np.arange(0,15)                                      

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
np.arange(10,30,5)                                          #start,stop,jump

array([10, 15, 20, 25])

In [10]:
a1=np.arange(16).reshape(4,4)

In [107]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])