# SCIPY LIBRARY

In [1]:
import numpy as np
import pandas as pd
import scipy as sc
import scipy.stats as st  #from scipy import stats as st
import warnings
warnings.filterwarnings('ignore')

In [2]:
a=np.array([15,20,25,30,35,40,45,50,55,60,81])
a

array([15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 81])

In [3]:
np.mean(a)

41.45454545454545

In [4]:
sc.mean(a)

41.45454545454545

In [5]:
sc.median(a)

40.0

In [6]:
round(sc.mean(a),2)

41.45

In [7]:
b=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [8]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
sc.mean(b)

50.0

In [10]:
sc.median(b)

50.0

In [11]:
sc.mean((b),axis=0)

array([40., 50., 60.])

In [12]:
sc.mean((b),axis=1)

array([20., 50., 80.])

In [13]:
sc.median((b),axis=0)

array([40., 50., 60.])

In [14]:
sc.median((b),axis=1)

array([20., 50., 80.])

In [15]:
st.mode(b)

ModeResult(mode=array([[10, 20, 30]]), count=array([[1, 1, 1]]))

In [16]:
st.mode((b),axis=0)

ModeResult(mode=array([[10, 20, 30]]), count=array([[1, 1, 1]]))

In [17]:
c=np.array([[2,3,4,15,6,7,2],[3,5,16,15,4,7,3],[3,6,4,8,7,2,12]])

In [18]:
c

array([[ 2,  3,  4, 15,  6,  7,  2],
       [ 3,  5, 16, 15,  4,  7,  3],
       [ 3,  6,  4,  8,  7,  2, 12]])

In [19]:
st.mode(c)

ModeResult(mode=array([[ 3,  3,  4, 15,  4,  7,  2]]), count=array([[2, 1, 2, 2, 1, 2, 1]]))

In [20]:
st.mode((c),axis=1)

ModeResult(mode=array([[2],
       [3],
       [2]]), count=array([[2],
       [2],
       [1]]))

In [21]:
d=np.array([[2,3,4,15,6,7,2,18,12,22],[3,5,16,15,4,7,3,9,12,24],[3,6,4,8,7,2,12,6,12,25]])

In [22]:
d

array([[ 2,  3,  4, 15,  6,  7,  2, 18, 12, 22],
       [ 3,  5, 16, 15,  4,  7,  3,  9, 12, 24],
       [ 3,  6,  4,  8,  7,  2, 12,  6, 12, 25]])

In [23]:
st.mode(d)

ModeResult(mode=array([[ 3,  3,  4, 15,  4,  7,  2,  6, 12, 22]]), count=array([[2, 1, 2, 2, 1, 2, 1, 1, 3, 1]]))

In [24]:
st.mode(d,axis=1)

ModeResult(mode=array([[2],
       [3],
       [6]]), count=array([[2],
       [2],
       [2]]))

In [25]:
from scipy.stats import percentileofscore as psc

In [41]:
marks=pd.read_csv('marks1.csv')
marks

Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45         56       87       21   
1    Suresh      M  04-05-1987     75       96         78       64       90   
2    Ramesh      M  25-05-1989     25       54         89       76       95   
3   Jessica      F  12-08-1990     78       96         86       63       54   
4  Jennifer      F  02-09-1989     58       96         78       46       96   
5      Annu      F  05-04-1988     45       87         52       89       55   
6     pooja      F  04-05-1987     55       64         61       58       75   
7    Ritesh      M  25-05-1989     54       76         87       56       25   
8     Farha      F  12-08-1990     55       63         89       75       78   
9    Mukesh      M  02-09-1989     96       46         77       83       58   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53  
5         89       87      52  
6         58       64      61  
7         56       76      87  
8         75       63      89  
9         83       46      77

In [27]:
psc(marks['Civics'],25)

10.0

In [28]:
psc(marks['Biology'],35)

20.0

In [29]:
mx=marks['Maths'].max()
mn=marks['Maths'].min()
rng=mx-mn   #spread of the data
rng

71

In [30]:
marks['Maths'].var()

378.71111111111105

In [31]:
marks['Chemistry'].var()

196.01111111111112

In [32]:
print(marks['Biology'].var())
print(marks['Civics'].var())

728.9000000000001
642.2777777777778


In [96]:
from scipy.stats import zscore

In [39]:
zscore([15,75,84,36,88])

array([-1.54156468,  0.53228915,  0.84336723, -0.81571584,  0.98162415])

In [97]:
zscore(marks['Biology'])

0   -1.706185
1    0.987792
2    1.183007
3   -0.417762
4    1.222050
5   -0.378718
6    0.402144
7   -1.550013
8    0.519274
9   -0.261589
Name: Biology, dtype: float64

In [68]:
qn1=marks['Maths'].quantile(0.60)
qn1

56.199999999999996

In [69]:
qn1=marks['Biology'].quantile(0.60)
qn1

76.2

In [84]:
qn3=marks['History'].quantile(0.75)
qn3

81.25

In [86]:
qn4=marks['History'].quantile(0.25)
qn4

59.25

In [88]:
IQR=qn3-qn4
IQR

22.0

In [98]:
zscore(marks['Maths'])

0   -0.249162
1    0.834152
2   -1.874135
3    0.996650
4   -0.086665
5   -0.790820
6   -0.249162
7   -0.303328
8   -0.249162
9    1.971633
Name: Maths, dtype: float64

In [99]:
zscore(marks['English'])

0    1.261699
1   -0.415704
2    0.459463
3   -0.488635
4   -1.728454
5    1.407560
6   -0.853288
7   -0.999149
8    0.386532
9    0.969976
Name: English, dtype: float64

In [100]:
marks.describe()

Maths    Physics  Chemistry    English    Biology  Economics  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   59.600000  72.300000  75.300000  69.700000  64.700000  72.700000   
std    19.460501  20.661559  14.000397  14.453373  26.998148  14.629119   
min    25.000000  45.000000  52.000000  46.000000  21.000000  52.000000   
25%    54.250000  56.250000  65.000000  59.250000  54.250000  58.750000   
50%    55.000000  70.000000  78.000000  69.500000  66.500000  76.000000   
75%    70.750000  93.750000  86.750000  81.250000  87.000000  86.000000   
max    96.000000  96.000000  89.000000  89.000000  96.000000  89.000000   

         History   Civics  
count  10.000000  10.0000  
mean   69.700000  60.5000  
std    14.453373  25.3432  
min    46.000000   2.0000  
25%    59.250000  52.2500  
50%    69.500000  63.0000  
75%    81.250000  76.2500  
max    89.000000  89.0000

In [52]:
data=pd.read_csv('president.csv')
data

order                    name  height
0       1       George Washington     189
1       2              John Adams     170
2       3        Thomas Jefferson     189
3       4           James Madison     163
4       5            James Monroe     183
5       6       John Quincy Adams     171
6       7          Andrew Jackson     185
7       8        Martin Van Buren     168
8       9  William Henry Harrison     173
9      10              John Tyler     183
10     11           James K. Polk     173
11     12          Zachary Taylor     173
12     13        Millard Fillmore     175
13     14         Franklin Pierce     178
14     15          James Buchanan     183
15     16         Abraham Lincoln     193
16     17          Andrew Johnson     178
17     18        Ulysses S. Grant     173
18     19     Rutherford B. Hayes     174
19     20       James A. Garfield     183
20     21       Chester A. Arthur     183
21     23       Benjamin Harrison     168
22     25        William McKinley     170
23     26      Theodore Roosevelt     178
24     27     William Howard Taft     182
25     28          Woodrow Wilson     180
26     29       Warren G. Harding     183
27     30         Calvin Coolidge     178
28     31          Herbert Hoover     182
29     32   Franklin D. Roosevelt     188
30     33         Harry S. Truman     175
31     34    Dwight D. Eisenhower     179
32     35         John F. Kennedy     183
33     36       Lyndon B. Johnson     193
34     37           Richard Nixon     182
35     38             Gerald Ford     183
36     39            Jimmy Carter     177
37     40           Ronald Reagan     185
38     41       George H. W. Bush     188
39     42            Bill Clinton     188
40     43          George W. Bush     182
41     44            Barack Obama     185

In [57]:
zscore(data['height'])

0     1.336139
1    -1.404835
2     1.336139
3    -2.414667
4     0.470568
5    -1.260573
6     0.759092
7    -1.693358
8    -0.972050
9     0.470568
10   -0.972050
11   -0.972050
12   -0.683526
13   -0.250741
14    0.470568
15    1.913186
16   -0.250741
17   -0.972050
18   -0.827788
19    0.470568
20    0.470568
21   -1.693358
22   -1.404835
23   -0.250741
24    0.326306
25    0.037783
26    0.470568
27   -0.250741
28    0.326306
29    1.191877
30   -0.683526
31   -0.106479
32    0.470568
33    1.913186
34    0.326306
35    0.470568
36   -0.395002
37    0.759092
38    1.191877
39    1.191877
40    0.326306
41    0.759092
Name: height, dtype: float64

In [90]:
q1=data['height'].quantile(0.25)
q1

174.25

In [89]:
q3=data['height'].quantile(0.75)
q3

183.0

In [91]:
IQR=q3-q1
IQR

8.75

In [103]:
data.describe()

order      height
count  42.000000   42.000000
mean   22.476190  179.738095
std    13.152461    7.015869
min     1.000000  163.000000
25%    11.250000  174.250000
50%    22.000000  182.000000
75%    33.750000  183.000000
max    44.000000  193.000000